/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaoyunchengzhu_jni_JniUtils */

#ifndef _Included_com_xiaoyunchengzhu_jni_JniUtils
#define _Included_com_xiaoyunchengzhu_jni_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaoyunchengzhu_jni_JniUtils
 * Method:    byteToStr
 * Signature: ([BLcom/xiaoyunchengzhu/jni/JniCallBack;)V
 */
JNIEXPORT void JNICALL Java_com_xiaoyunchengzhu_jni_JniUtils_byteToStr
  (JNIEnv *, jobject, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
