/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jniutil.h"



jobject newJniResult(JNIEnv *env,jbyteArray data){
    jclass decodeResultC=(*env)->FindClass(env,"com/xiaoyunchengzhu/jni/JniResult");
    if (decodeResultC==NULL){
        return NULL;
    }
    //获取构造方法id
    jmethodID constructor = (*env)->GetMethodID(env,decodeResultC, "<init>", "([BLjava/lang/String;)V");
    if (NULL == constructor) {
        return NULL;
    }

    char  *bytes=(*env)->GetByteArrayElements(env,data,0);
    jstring jstr=(*env)->NewStringUTF(env,bytes);
    return (*env)->NewObject(env,decodeResultC,constructor,data,jstr);
}

/*
 * Class:     com_xiaoyunchengzhu_jni_JniUtils
 * Method:    byteToStr
 * Signature: ([BLcom/xiaoyunchengzhu/jni/JniCallBack;)V
 */
JNIEXPORT void JNICALL Java_com_xiaoyunchengzhu_jni_JniUtils_byteToStr
  (JNIEnv *env, jobject object, jbyteArray data, jobject callback){


    jobject  result= newJniResult(env,data);
    jclass jniCallBackClass=(*env)->FindClass(env,"com/xiaoyunchengzhu/jni/JniCallBack");
    jmethodID callMethod=(*env)->GetMethodID(env,jniCallBackClass,"decodeResponse","(Lcom/xiaoyunchengzhu/jni/JniResult;)V");
    (*env)->CallVoidMethod(env,callback,callMethod,result);
}

